In [ ]:
#import required lib
import numpy as np
import math

In [ ]:
#creating random array from 1 to 200
random_arr = np.random.randint(1,201,(10,10))
random_arr

array([[173, 191,  77, 154,  27, 134,  49,  84,  19,  67],
       [174, 106,  27, 193,   4, 196,  41,  23,  90,  58],
       [121, 169,  43, 139,  45, 192, 178,  42, 152,  64],
       [122,  24, 116, 162,  37,  49, 160, 143, 108,  14],
       [137,  55,  76, 153, 170, 171, 168,  68, 180,  77],
       [173,  73,  70, 117,  83,  92,  97, 182, 166, 165],
       [ 85,  49, 184, 122,   9, 180,  93,  83,   6, 100],
       [  4,   4, 165, 148,  92, 190, 106,  81, 109,  82],
       [ 56,  54, 129, 106, 187, 145, 122, 103,  96,  67],
       [125, 124,  40,  47,   5,  12,  14,  22,  82, 101]])

In [ ]:

# sigmoid custom function
def sigmoid(x):
  return 1 / (1 + np.exp(-x))

sigmoid(random_arr) 

array([[1.        , 0.88079708, 1.        , 1.        , 1.        ,
        1.        , 1.        , 1.        , 1.        , 1.        ],
       [1.        , 1.        , 1.        , 1.        , 1.        ,
        1.        , 1.        , 1.        , 1.        , 1.        ],
       [1.        , 0.99999917, 1.        , 1.        , 1.        ,
        1.        , 1.        , 1.        , 1.        , 1.        ],
       [1.        , 1.        , 1.        , 0.99999917, 0.99908895,
        1.        , 1.        , 1.        , 1.        , 1.        ],
       [1.        , 1.        , 1.        , 1.        , 1.        ,
        1.        , 1.        , 1.        , 1.        , 1.        ],
       [1.        , 1.        , 1.        , 1.        , 1.        ,
        1.        , 1.        , 1.        , 1.        , 1.        ],
       [1.        , 1.        , 1.        , 1.        , 1.        ,
        1.        , 1.        , 1.        , 1.        , 1.        ],
       [1.        , 1.        , 0.9999999

In [ ]:
#Apply custom normalization on the array
normalised_arr = (random_arr - np.min(random_arr))/np.ptp(random_arr)
normalised_arr

array([[0.88020833, 0.97395833, 0.38020833, 0.78125   , 0.11979167,
        0.67708333, 0.234375  , 0.41666667, 0.078125  , 0.328125  ],
       [0.88541667, 0.53125   , 0.11979167, 0.984375  , 0.        ,
        1.        , 0.19270833, 0.09895833, 0.44791667, 0.28125   ],
       [0.609375  , 0.859375  , 0.203125  , 0.703125  , 0.21354167,
        0.97916667, 0.90625   , 0.19791667, 0.77083333, 0.3125    ],
       [0.61458333, 0.10416667, 0.58333333, 0.82291667, 0.171875  ,
        0.234375  , 0.8125    , 0.72395833, 0.54166667, 0.05208333],
       [0.69270833, 0.265625  , 0.375     , 0.77604167, 0.86458333,
        0.86979167, 0.85416667, 0.33333333, 0.91666667, 0.38020833],
       [0.88020833, 0.359375  , 0.34375   , 0.58854167, 0.41145833,
        0.45833333, 0.484375  , 0.92708333, 0.84375   , 0.83854167],
       [0.421875  , 0.234375  , 0.9375    , 0.61458333, 0.02604167,
        0.91666667, 0.46354167, 0.41145833, 0.01041667, 0.5       ],
       [0.        , 0.        , 0.8385416

In [ ]:
#Apply custom standardization on the array
s_a = (random_arr - np.mean(random_arr)) / np.std(random_arr)
s_a

array([[ 1.29062623,  1.60751713, -0.39945859,  0.95613028, -1.2797111 ,
         0.60402927, -0.89239999, -0.27622324, -1.4205515 , -0.57550909],
       [ 1.30823128,  0.11108787, -1.2797111 ,  1.64272723, -1.68462725,
         1.69554239, -1.0332404 , -1.3501313 , -0.17059294, -0.73395454],
       [ 0.37516362,  1.22020603, -0.9980303 ,  0.69205452, -0.9628202 ,
         1.62512218,  1.37865148, -1.01563535,  0.92092018, -0.62832424],
       [ 0.39276867, -1.33252625,  0.28713837,  1.09697068, -1.1036606 ,
        -0.89239999,  1.06176058,  0.76247472,  0.14629797, -1.50857675],
       [ 0.65684442, -0.78676969, -0.41706364,  0.93852523,  1.23781108,
         1.25541613,  1.20260098, -0.55790404,  1.41386158, -0.39945859],
       [ 1.29062623, -0.46987879, -0.52269394,  0.30474342, -0.29382829,
        -0.13538284, -0.04735759,  1.44907168,  1.16739088,  1.14978583],
       [-0.25861819, -0.89239999,  1.48428178,  0.39276867, -1.596602  ,
         1.41386158, -0.11777779, -0.29382829